# Generated by Django 5.2.12 on 2026-03-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], max_length=1)),
                ('department', models.CharField(max_length=100)),
                ('preferred_project_type', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('networking', 'Networking'), ('cybersecurity', 'Cybersecurity'), ('software_engineering', 'Software Engineering'), ('other', 'Other')], max_length=50)),
                ('preferred_location', models.CharField(choices=[('gaborone', 'Gaborone'), ('francistown', 'Francistown'), ('maun', 'Maun'), ('kasane', 'Kasane'), ('serowe', 'Serowe'), ('palapye', 'Palapye'), ('other', 'Other')], max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('is_placed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
