# Generated by Django 5.2.12 on 2026-03-21 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('industry', models.CharField(choices=[('information_technology', 'Information Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('telecommunications', 'Telecommunications'), ('government', 'Government'), ('other', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('preferred_skills', models.JSONField(default=list)),
                ('preferred_project_type', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('networking', 'Networking'), ('cybersecurity', 'Cybersecurity'), ('software_engineering', 'Software Engineering'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(choices=[('gaborone', 'Gaborone'), ('francistown', 'Francistown'), ('maun', 'Maun'), ('kasane', 'Kasane'), ('serowe', 'Serowe'), ('palapye', 'Palapye'), ('other', 'Other')], max_length=50)),
                ('max_students', models.IntegerField(default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
