# Generated by Django 5.2.12 on 2026-04-26 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industrial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('university_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment_count', models.PositiveSmallIntegerField(default=0)),
                ('industrial_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('university_weight', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_record', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='IndustrialSupervisorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('strengths', models.TextField()),
                ('improvement_areas', models.TextField()),
                ('attendance_comment', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industrial_supervisor_reports', to='organizations.organizationprofile')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_supervisor_report', to='students.studentprofile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_industrial_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='final_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_attachment_report', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentWeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('highlights', models.TextField()),
                ('tasks_completed', models.TextField()),
                ('challenges', models.TextField(blank=True, default='')),
                ('next_steps', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-week_number', '-updated_at'],
                'unique_together': {('student', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='UniversitySupervisorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_number', models.PositiveSmallIntegerField(choices=[(1, 'Assessment 1'), (2, 'Assessment 2')])),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True, default='')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_supervisor_assessments', to='students.studentprofile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_university_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name', 'assessment_number'],
                'unique_together': {('student', 'assessment_number')},
            },
        ),
    ]
